//==================================================
// This file contains the Excluded objects
// Generated By User: ord1nary
// Format Version: 2
// Date: Wed Sep 11 23:42:59 2024
// ExclMode: default
//==================================================
CHECKSUM: "251954004"
INSTANCE:tb.i_cpu_soc.i_insn_mem
CHECKSUM: "251954004"
INSTANCE:tb.i_cpu_soc.i_data_mem
CHECKSUM: "153172799"
INSTANCE:tb.input_if
CHECKSUM: "153172799"
INSTANCE:tb.output_if
CHECKSUM: "473042511 3908094873"
INSTANCE: tb.i_cpu_soc.i_cpu.i_registers
Toggle 1to0 rstn_i "net rstn_i"
Toggle reg_x0 "net reg_x0[31:0]"
